<%_ if (searchEngine == 'elasticsearch') { _%>
<%= baseName.toLowerCase() %>-app-elasticsearch:
    container_name: <%= baseName.toLowerCase() %>-app-elasticsearch
    image: elasticsearch:<%= dockerVersionSE %>
    <%_ if (dockerVolume) { _%>
    volumes:
        - <%= dockerVolumePath %>/<%= baseName %>/elasticsearch/:/usr/share/elasticsearch/data/
        <%_ } _%>
    ports:
        - "9200:9200"
        - "9300:9300"
<%_ } if (prodDatabaseType == 'mysql') { _%>
<%= baseName.toLowerCase() %>-app-mysql:
    container_name: <%= baseName.toLowerCase() %>-app-mysql
    image: mysql:<%= dockerVersionDB %>
    <%_ if (dockerVolume) { _%>
    volumes:
        - <%= dockerVolumePath %>/<%= baseName %>/mysql/:/var/lib/mysql/
    <%_ } _%>
    environment:
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=<%= baseName.toLowerCase() %>
    ports:
        - "3306:3306"
    command: mysqld --lower_case_table_names=1
<%_ } if (prodDatabaseType == 'postgresql') { _%>
<%= baseName.toLowerCase() %>-app-postgresql:
    container_name: <%= baseName.toLowerCase() %>-app-postgresql
    image: postgres:<%= dockerVersionDB %>
    <%_ if (dockerVolume) { _%>
    volumes:
        - <%= dockerVolumePath %>/<%= baseName %>/postgresql/:/var/lib/postgresql/
    <%_ } _%>
    environment:
        - POSTGRES_USER=<%= baseName %>
        - POSTGRES_PASSWORD=
    ports:
        - "5432:5432"
<%_ } if (prodDatabaseType == 'mongodb') { _%>
<%= baseName.toLowerCase() %>-app-mongodb:
    container_name: <%= baseName.toLowerCase() %>-app-mongodb
    image: mongo:<%= dockerVersionDB %>
    <%_ if (dockerVolume) { _%>
    volumes:
        - <%= dockerVolumePath %>/<%= baseName %>/mongodb/:/data/db/
    <%_ } _%>
    ports:
        - "27017:27017"
<%_ } _%>
<%= baseName.toLowerCase() %>-app:
    container_name: <%= baseName.toLowerCase() %>-app
    <%_ if (dockerType == 'automated') { _%>
    image: <%=dockerLogin.toLowerCase()%>/<%=dockerNameGithub.toLowerCase()%>
    <%_ } else { _%>
    image: <%=dockerLogin.toLowerCase()%>/<%= baseName.toLowerCase() %><% if (dockerType == 'dockerpush') { %>:<%= dockerTag %><% } %>
    <%_ } _%>
    ports:
        - "8080:8080"
    <%_ if (prodDatabaseType == 'cassandra') { _%>
    external_links:
        - "<%= baseName.toLowerCase() %>-app-cassandra:cassandra"
    <%_ } else { _%>
    links:
        <%_ if (searchEngine == 'elasticsearch') { _%>
        - "<%= baseName.toLowerCase() %>-app-elasticsearch:elastic"
        <%_ } if (prodDatabaseType == 'mysql') { _%>
        - "<%= baseName.toLowerCase() %>-app-mysql:mysql"
        <%_ } if (prodDatabaseType == 'postgresql') { _%>
        - "<%= baseName.toLowerCase() %>-app-postgresql:postgresql"
        <%_ } if (prodDatabaseType == 'mongodb') { _%>
        - "<%= baseName.toLowerCase() %>-app-mongodb:mongodb"
        <%_ } _%>
    <%_ } _%>
