<%_ if (searchEngine == 'elasticsearch') { _%>
<%= baseName.toLowerCase() %>-elasticsearch:
    container_name: <%= baseName.toLowerCase() %>-elasticsearch
    image: elasticsearch:<%= dockerVersionSE %>
    <%_ if (dockerVolume) { _%>
    volumes:
        - <%= dockerVolumePath %>/<%= baseName %>/elasticsearch/:/usr/share/elasticsearch/data/
    <%_ } _%>
    ports:
        - "9200:9200"
        - "9300:9300"
<%_ } if (prodDatabaseType == 'mysql') { _%>
<%= baseName.toLowerCase() %>-mysql:
    container_name: <%= baseName.toLowerCase() %>-mysql
    image: mysql:<%= dockerVersionDB %>
    <%_ if (dockerVolume) { _%>
    volumes:
        - <%= dockerVolumePath %>/<%= baseName %>/mysql/:/var/lib/mysql/
    <%_ } _%>
    environment:
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=<%= baseName.toLowerCase() %>
    ports:
        - "3306:3306"
    command: mysqld --lower_case_table_names=1
<%_ } if (prodDatabaseType == 'postgresql') { _%>
<%= baseName.toLowerCase() %>-postgresql:
    container_name: <%= baseName.toLowerCase() %>-postgresql
    image: postgres:<%= dockerVersionDB %>
    <%_ if (dockerVolume) { _%>
    volumes:
        - <%= dockerVolumePath %>/<%= baseName %>/postgresql/:/var/lib/postgresql/
    <%_ } _%>
    environment:
        - POSTGRES_USER=<%= baseName %>
        - POSTGRES_PASSWORD=
    ports:
        - "5432:5432"
<%_ } if (prodDatabaseType == 'mongodb') { _%><%= baseName.toLowerCase() %>-mongodb:
    container_name: <%= baseName.toLowerCase() %>-mongodb
    image: mongo:<%= dockerVersionDB %>
    <%_ if (dockerVolume) { _%>
    volumes:
       - <%= dockerVolumePath %>/<%= baseName %>/mongodb/:/data/db/
    <%_ } _%>
    ports:
        - "27017:27017"
<%_ } if (prodDatabaseType == 'cassandra') { _%>
<%= baseName.toLowerCase() %>-opscenter:
    container_name: <%= baseName.toLowerCase() %>-opscenter
    build: ./docker/cassandra
    dockerfile: Opscenter.Dockerfile
    ports:
        - "8888:8888"
<%= baseName.toLowerCase() %>-cassandra:
    container_name: <%= baseName.toLowerCase() %>-cassandra
    build: .
    dockerfile: Cassandra.Dockerfile
    <%_ if (dockerVolume) { _%>
    volumes:
       - <%= dockerVolumePath %>/<%= baseName %>/cassandra/:/var/lib/cassandra/data
    <%_ } _%>
    links:
        - <%= baseName.toLowerCase() %>-opscenter:opscenter
    ports:
        - "7000:7000"
        - "7001:7001"
        - "7199:7199"
        - "9042:9042"
        - "9160:9160"
<%= baseName.toLowerCase() %>-cassandra-node:
    build: .
    dockerfile: Cassandra.Dockerfile
    links:
        - <%= baseName.toLowerCase() %>-cassandra:seed
        - <%= baseName.toLowerCase() %>-opscenter:opscenter
    environment:
        - CASSANDRA_SEEDS=seed
<%_ } _%>
