<% if (devDatabaseType == 'mysql') { %><%=baseName.toLowerCase()%>-dev-mysql:
    container_name: <%=baseName.toLowerCase()%>-dev-mysql
    image: mysql:<%=dockerVersionSE%><% if (dockerVolume) { %>
    volumes:
        - <%=dockerVolumePath%>/<%=baseName%>/dev-mysql/:/var/lib/mysql/<% } %>
    environment:
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=<%=baseName.toLowerCase()%>
    ports:
        - "3306:3306"
    command: mysqld --lower_case_table_names=1
<% } if (devDatabaseType == 'postgresql') { %><%=baseName.toLowerCase()%>-dev-postgresql:
    container_name: <%=baseName.toLowerCase()%>-dev-postgresql
    image: postgres:<%=dockerVersionDB%><% if (dockerVolume) { %>
    volumes:
      - <%=dockerVolumePath%>/<%=baseName%>/dev-postgresql/:/var/lib/postgresql/<% } %>
    environment:
        - POSTGRES_USER=<%=baseName%>
        - POSTGRES_PASSWORD=
    ports:
        - "5432:5432"
<% } if (devDatabaseType == 'mongodb') { %><%=baseName.toLowerCase()%>-dev-mongodb:
    container_name: <%=baseName.toLowerCase()%>-dev-mongodb
    image: mongo:<%=dockerVersionDB%><% if (dockerVolume) { %>
    volumes:
        - <%=dockerVolumePath%>/<%=baseName%>/dev-mongodb/:/data/db/<% } %>
    ports:
        - "27017:27017"
<% } if (devDatabaseType == 'cassandra') { %><%=baseName.toLowerCase()%>-dev-cassandra:
    container_name: <%=baseName.toLowerCase()%>-dev-cassandra
    build: .
    dockerfile: Cassandra.Dockerfile<% if (dockerVolume) { %>
    volumes:
        - <%=dockerVolumePath%>/<%=baseName%>/dev-cassandra/:/var/lib/cassandra/data<% } %>
    ports:
        - "7000:7000"
        - "7001:7001"
        - "7199:7199"
        - "9042:9042"
        - "9160:9160"
<% } %>
