<%_ if (devDatabaseType == 'mysql') { _%>
<%= baseName.toLowerCase() %>-dev-mysql:
  container_name: <%= baseName.toLowerCase() %>-dev-mysql
  image: mysql:<%= dockerVersionDB %>
  <%_ if (dockerVolume) { _%>
  volumes:
    - <%= dockerVolumePath %>/<%= baseName %>/dev-mysql/:/var/lib/mysql/
  <%_ } else { _%>
  # volumes:
  #   - ~/volumes/jhipster/<%= baseName %>/dev-mysql/:/var/lib/mysql/
  <%_ } _%>
  environment:
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=<%= baseName.toLowerCase() %>
  ports:
    - "3306:3306"
  command: mysqld --lower_case_table_names=1
<%_ } _%>
<%_ if (devDatabaseType == 'postgresql') { _%>
<%= baseName.toLowerCase() %>-dev-postgresql:
  container_name: <%= baseName.toLowerCase() %>-dev-postgresql
  image: postgres:<%= dockerVersionDB %>
  <%_ if (dockerVolume) { _%>
  volumes:
    - <%= dockerVolumePath %>/<%= baseName %>/dev-postgresql/:/var/lib/postgresql/
  <%_ } else { _%>
  # volumes:
  #   - ~/volumes/jhipster/<%= baseName %>/dev-postgresql/:/var/lib/postgresql/
  <%_ } _%>
  environment:
    - POSTGRES_USER=<%= baseName %>
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
<%_ } _%>
<%_ if (devDatabaseType == 'mongodb') { _%>
<%= baseName.toLowerCase() %>-dev-mongodb:
  container_name: <%= baseName.toLowerCase() %>-dev-mongodb
  image: mongo:<%= dockerVersionDB %>
  <%_ if (dockerVolume) { _%>
  volumes:
    - <%= dockerVolumePath %>/<%= baseName %>/dev-mongodb/:/data/db/
  <%_ } else { _%>
  # volumes:
  #   - ~/volumes/jhipster/<%= baseName %>/dev-mongodb/:/data/db/
  <%_ } _%>
  ports:
    - "27017:27017"
<%_ } _%>
<%_ if (devDatabaseType == 'cassandra') { _%>
<%= baseName.toLowerCase() %>-dev-cassandra:
  container_name: <%= baseName.toLowerCase() %>-dev-cassandra
  build: .
  dockerfile: Cassandra-Dev.Dockerfile
  <%_ if (dockerVolume) { _%>
  volumes:
    - <%= dockerVolumePath %>/<%= baseName %>/dev-cassandra/:/var/lib/cassandra/data
  <%_ } else { _%>
  # volumes:
  #   - ~/volumes/jhipster/<%= baseName %>/dev-cassandra/:/var/lib/cassandra/data
  <%_ } _%>
  ports:
    - "7000:7000"
    - "7001:7001"
    - "7199:7199"
    - "9042:9042"
    - "9160:9160"
<%_ } _%>
