os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "8.9.3"
before_install:
    - npm install -g npm
    # Repo for Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn global add yo
install:
    - yarn install
    - yarn global add file:"$TRAVIS_BUILD_DIR"
    - yarn test
script:
    - git clone https://github.com/jhipster/jhipster-sample-app.git
    - cd jhipster-sample-app
    - yo jhipster-docker default --force
    - docker build -t jhipster-sample-app .
    - docker images
