os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "6.9.1"
cache:
    directories:
        - node_modules
before_install:
    # Repo for Yarn
    - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq yarn
    - yarn global add yo gulp-cli
install:
    - yarn install
    - yarn link
    - yarn run test
script:
    - git clone https://github.com/pascalgrimaud/jhipster-sample-app.git
    - cd jhipster-sample-app
    - yo jhipster-docker default --force --yarn
    - docker build -t jhipster-sample-app .
    - docker images
