os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "6.11.0"
before_install:
    - npm install -g npm
    - npm install -g yarn
    - yarn global add yo
install:
    - yarn install
    - yarn link
    - gulp eslint
    - gulp test
script:
    - git clone https://github.com/jhipster/jhipster-sample-app-ng2.git
    - cd jhipster-sample-app-ng2
    - yarn link generator-jhipster-docker
    - yo jhipster-docker --default --force
    - docker build -t jhipster-sample-app .
    - docker images
